### ISSUE TITLE
Bad Code?

### ISSUE THREAD

**Issue by Oassiss76** [robbiebarrat/twitter-contest-enterer#13]
So I tried out the bot, and I keep on getting this error code: https://gyazo.com/2c50597ce9fdf722020e9f0584d563f6

**Comment by robbiebarrat** [comment]
you're using python 3, while this code is written in python 2.7

change all of the print statements from

`print "something" + "somethine else"`

to 

`print("something" + "something else")`

just wrap it in parenthesis and remove the space immediately after the word `print` and it should work.

**Comment by Oassiss76** [comment]
It worked, thank you so much

**Comment by dimitrilap** [comment]
@robbiebarrat This issue can probably be closed, right? Sorry to bother you.

**Comment by robbiebarrat** [comment]
haha you're good - saw this and totally forgot. closing now
