### ISSUE TITLE
Managed to modify the script to work with Python 3.

### ISSUE THREAD

**Issue by dimitrilap** [robbiebarrat/twitter-contest-enterer#15]
Wondering if you would be interested in creating a separate branch for Python 3. If so I could make a pull request.

**Comment by robbiebarrat** [comment]
totally - make a pull request and i'll check it out

**Comment by dimitrilap** [comment]
@robbiebarrat Done! Wasn't able to make it as a separate branch. However, if you would be open to converting the project to Python 3 I would start working on a GUI or CLI (Possibly Both) depending on request.

https://github.com/robbiebarrat/twitter-contest-enterer/pull/16

**Comment by robbiebarrat** [comment]
I'm really busy with newer projects right now- so I doubt that I'll add any features, but if you submit any pull requests i'll be happy to check them out / merge them into master.

**Comment by dimitrilap** [comment]
@robbiebarrat Sorry to bother you again. Wondering if you would be open to letting some maintainers do basic fixes and improve upon things. I would be happy to do it as I need a project to keep my skills fresh without too much to worry about. But for now, #16 is my pull request for the Python 3 fix.

**Comment by robbiebarrat** [comment]
@dimitrilap just added you as a collaborator - should let you upkeep/improve the project if you'd like.

**Comment by dimitrilap** [comment]
@robbiebarrat Thanks so much, I'll get to work!
