### ISSUE TITLE
Feature request: Blacklist bot spotters

### ISSUE THREAD

**Issue by ghost** [robbiebarrat/twitter-contest-enterer#2]
These accounts release fake contests to detect bots.

https://twitter.com/RealBotSp0tter
https://twitter.com/RealBotSpotter
https://twitter.com/RealB0tSpotter

 If we win a contest and they find one of these tweets in our timeline they will find out we are a bot.

I tried muting and blocking them but it doesn't work, the bot eventually follows the account and it unblocks again. They don't use the same text so there is nothing to blacklist, the only thing consistent is the username.

It would be great if you could add a way to blacklist a twitter user just like we can blacklist a keyword.

Thank you for your time.

**Comment by robbiebarrat** [comment]
Yes this is a problem.

I noticed that the botspotter accounts post the same picture of a robot with every tweet, but it would be quicker to check for username (you could easily just get the username, replace all of the 0's with o's, and look for the word "spot" or "bot"... Hold on, putting something together really quick...

**Comment by robbiebarrat** [comment]
Alright - just added something that should keep it from retweeting any of those bot spotter accounts. If this doesn't work, just comment and i'll reopen the issue.
