### ISSUE TITLE
My bot keeps retweeting false contests

### ISSUE THREAD

**Issue by PascalvanDongen** [robbiebarrat/twitter-contest-enterer#3]
My bot keeps retweeting contests from the user: @lvbroadcasting. If i block the user on twitter it keeps unblocking it. I also tried to add words to the bannedwords section in the twitterbot.py. I changed it to this: ` bannedwords = ["vote", "bot", "b0t", "lvbroadcasting" "Las", "Vegas", "TV"]`, but it didn't work. What do i need to change in the code to make it work? Thanks!

**Comment by robbiebarrat** [comment]
I just updated it and added this list called "bannedusers" - and put lvbroadcasting in it.

I know there are a ton of users like "botspotter", "b0tspotter", "sp0tbots", etc, so if you just put "bot" the `bannedusers` list, it'll take care of all of those. it'll stop retweeting any user that has that in their username.

**Comment by AfwasSysteem** [comment]
I used the update, but it still retweets tweets from lvbroadcasting. I noticed that for the `bannedwords` section you use "" to put words in, and in the `bannedusers` section you use ''. Can that make a difference for it to work?
Thanks, 
Pascal

**Comment by robbiebarrat** [comment]
Could you link me to lvbroadcasting's twitter profile?

**Comment by AfwasSysteem** [comment]
https://twitter.com/lvbroadcasting

**Comment by robbiebarrat** [comment]
alright - try it now. I have it scan both the screen name and handle; it should definitely work now - let me know if that isn't the case.

**Comment by AfwasSysteem** [comment]
Still does not work. The script runs for like 60 seconds, retweets a tweet from lvbroadcasting and than i get this error: `Traceback (most recent call last):
  File "twitterbot.py", line 67, in <module>
    run()
  File "twitterbot.py", line 62, in run
    search(api.search(q=key))
  File "twitterbot.py", line 37, in search
    if is_user_bot_hunter(str(i.author.name), str(i.author.screen_name)) == False:
UnicodeEncodeError: 'ascii' codec can't encode character u'\U0001f940' in position 4: ordinal not in range(128)
`
