### ISSUE TITLE
Still retweets lvbroadcasting

### ISSUE THREAD

**Issue by PascalvanDongen** [robbiebarrat/twitter-contest-enterer#4]
I used the update, but it still retweets tweets from lvbroadcasting. I noticed that for the `bannedwords` section you use "" to put words in, and in the `bannedusers` section you use ''. Can that make a difference for it to work?
Thanks, 
Pascal
P.S.: Also commented on my previous issue, then realized it was closed.

**Comment by robbiebarrat** [comment]
I'm reopening the old issue - #3
