### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by alexpereza4** [robbiebarrat/twitter-contest-enterer#9]
Hello,
I have a problem with the code and i dont know what is the problem

-contest-enterer-master> python twitterbot.py
  File "twitterbot.py", line 40
    print "rt " + (i.text)
              ^
SyntaxError: invalid syntax

Can Someone help me.
Thanks

**Comment by robbiebarrat** [comment]
i think you might be using python 3 - try changing the print statement to `print("rt " + (i.text))` and see if you start getting a different error

**Comment by realwakils** [comment]
Worked for me, thanks!
You can close this thread.
